#!/usr/bin/env python3
# In The Name Of God
# ========================================
# [] File Name : kaa
#
# [] Creation Date : 3/17/16
#
# [] Created By : Parham Alvani (parham.alvani@gmail.com)
# =======================================
from kaa.cli.cli import KaaCLICmd

try:
    KaaCLICmd().cmdloop()
except KeyboardInterrupt:
    quit(0)
