---
name: ci
on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: pip install pipenv
      - run: pipenv install --dev -v
      - run: pipenv run pytest
      - run: pipenv run mypy .
  docker:
    runs-on: ubuntu-latest
    needs:
      - test
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/bake-action@v2
        with:
          platforms: linux/amd64
          push: true
          files: 'docker-bake.json'
