---
name: ci
on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install pipenv
      - run: pipenv install --dev -v
      - run: pipenv run pytest
      - run: pipenv run mypy .
  docker:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/bake-action@v4
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          TAG: ${{ github.ref_name }}
        with:
          push: true
          files: 'docker-bake.json'
      - uses: docker/bake-action@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          push: true
          files: 'docker-bake.json'
